name: Daily Scrape

on:
  schedule:
    # Ejecutar todos los días a las 5:00 AM UTC (ajusta según la zona horaria que prefieras)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node scraper.js