name: Daily Excel Scraping

on:
  schedule:
  - cron: '0 5 * * *'  # scrapping, todos los dias, a las 1 (horario verano) o a las 2 (horario invierno)

  workflow_dispatch: # Permite ejecución manual desde la interfaz de GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
        # Cambiado de npm ci a npm install
      
      - name: Run scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node scraper.js
      
      - name: Archive Excel file
        uses: actions/upload-artifact@v4
        with:
          name: uai-eventos-excel
          path: downloads/*.xlsx
          retention-days: 7
